### PR TITLE
Unify StartChildResult and StartLinkResult types and provide helpers …

### PR DESCRIPTION
**Pull request by adrianroe**
…to check / extract the Pid

### CODE REVIEW

**Review by robashton — COMMENTED** [review]
So...

my only concern is that this is a step backwards from the original design goal of "Pinto looks like the OTP docs and avoids the pitfalls of low-level bindings where you have to use functions to interpret/use the underlying types".

start_child and start_link are explicitly different types in the OTP docs.

That said, I can see the appeal of Either as an abstract, are there other places in the Pinto codebase where this exercise could be carried out? Does anybody else have any thoughts before I merge this?

@philipstears @nwolverson 

I'm not fundamentally against it, it's just a change of direction - I think possibly for the best.

**Comment by philipstears** [comment]
I like the Either, but I'm not keen on unifying this way.

It seems to me that both functions have got a single obvious success case, a set of pre-defined and important "failure" cases , and then a whole universe of third party failure cases.

`start_child` also has another success case where it returns additional info from the `init` function that I don't think I've ever used, but I don't know if we want to rule out supporting.

This change makes the one obvious success case easy, at the price of making the pre-defined failures non-obvious because now they're no longer part of the type signature - instead we've got a foreign value we have to try to call some other function on to pull out information.

I'd personally rather all the documented errors came out in a typed fashion, e.g. maybe one has types that look like:

data StartChildRunning = ChildAlreadyStarted Pid | ChildStarted Pid | ChildStarted Pid Foreign
data StartChildError = ChildPresent | ChildFailed Foreign
type StartChildResult = Either StartChildError StartChildRunning

(I'm not happy about the foreigns, but that's probably an unresolveable issue).

I appreciate the desire to treat them as common, but if that's a desirable thing, couldn't we just do that with a simple type class `HasPid` with a single function returning `Maybe Pid`.

Just my 2p.

**Comment by robashton** [comment]
That is more in line with what Pinto was trying to do originally - avoiding low level bindings with foreigns and such.

Your above suggestion is a good compromise - I think it's worthwhile getting this right, as this is not an unusual scenario in our FFI.

**Comment by nwolverson** [comment]
Kind of on board with @philipstears. In general I'd try to avoid throwing `Foreign` around, I have a bad habit of being lazy and doing so, generally I'd state a preference when the native type is somewhat unknown/unrepresented/open-ended to use an opaque data type (a `foreign import data`) with accessors as needed

**Comment by adrianroe** [comment]
Thanks all for the feedback - and I agree it is a better way forward :)

I’ll implement more or less what @philipstears <https://github.com/philipstears> suggested with the minor difference that I’ll model {error, {already_started, Pid}} as a Left.  I’ll then do a type class based implementation for ok and okAlreadyStarted.

Wrt to the latter I think I’ll change the types to be

ok :: forall a. HasPid a => Effect Unit
okAlreadyStarted :: forall a. HasPid a => Effect Unit

And add in 
ok' :: forall a. HasPid a => Effect Pid
okAlreadyStarted' :: forall a. HasPid a => Effect Pid

95% of the time (in Purerl at least), you just want to check that the process started, not what the pid was and I’m keen to not see any _ <- lines scattered through our code (as I have done all over the place so far!)

Thanks again.

Adrian
_______________
Dr Adrian Roe
Director
www.id3as.com

**Comment by adrianroe** [comment]
OK, I went ahead with the above - albeit it had to be somewhat different to the discussed strategy.  You cannot have typeclasses for type (only newtype / data) so the Either structure did not really fit.  As a result both StartLinkResult and StartChildResult are now just ADTs that reflect all the Erlang options.  I then could use a typeclass 
```
class StartOk a where
  startOk :: a -> Maybe Pid
  startOkAS :: a -> Maybe Pid
```
To implement ok, okAlreadyStarted and ' variants.  RTSV2 is working OK with the changes.

Comments welcome again!

**Comment by robashton** [comment]
Totally missed this, as per recent work-swampage, will have a scan this weekend

**Pull request merged**
